server:
  port: 8981
logging:
  level: DEBUG
  level.org.springframework.web: DEBUG
  level.org.hibernate: ERROR
  file:
    name: 'LOGS/dev_app.log'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
telegram:
  bot:
    token: 
    username: 
spring:
  datasource:
#    url: jdbc:h2:./bd/help_bot_db;DB_CLOSE_ON_EXIT=TRUE
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: '!QAZxsw2'
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
#                  ddl-auto: create
      ddl-auto: update
    show-sql: false
setting-bot:
  path-input: '/input'
  file-name: 'dataset.txt'
  timeout: 1
